# Generated by Django 5.0.6 on 2024-06-21 07:57

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="rating",
            unique_together={("user", "movie")},
        ),
        migrations.AlterIndexTogether(
            name="rating",
            index_together={("user", "movie")},
        ),
    ]
